version: '2'
services:

  postgres:
    container_name: postgres
    image: postgres:10.4
    restart: always
    env_file:
      - env/db.env
    volumes:
      - ./Database/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./Database/postgres-data:/var/lib/postgresql/data
    expose:
      - 5432


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - env/pgadmin.env
    ports:
      - "5050:80"

  interface:
    container_name: interface
    build:
      context: ./ui
      dockerfile: Dockerfile
    devices:
      - "/dev/video0:/dev/video0"
    ports:
      - "80:8501"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - interface
    - postgres

volumes:
  postgres-data:
