scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: interface_metrics
  scrape_interval: 1s
  static_configs:
  - targets:
    - interface:9000